run: compile
    echo "# wasm3"
    echo "how_old" | wasm3 --repl how-old.wasm
    echo ""
    echo "# wasmtime"
    wasmtime --invoke how_old how-old.wasm 1980 2021

objdump: compile
    wasm-objdump -x how-old.wasm

compile:
    wat2wasm -o how-old.wasm how-old.wat

